feat: windows build (#327)
* Rename CALLBACK defined in Windows headers

* Rename interface defined in Windows headers

* Reuse SET_PROTOTYPE method from util.h

Fixes warning: SET_METHOD redefined

* Don't initialize array with a variable

Fixes MSVC Error C2131

* Remove GCC attribute MSVC doesn't know

At some point something like
https://stackoverflow.com/questions/4226308/msvc-equivalent-of-attribute-warn-unused-result/22759336#22759336
should be used

* Replace uint with guint

https://developer-old.gnome.org/gobject/stable/gobject-Closures.html#GClosureMarshal

* Move cflags & ldflags to Linux only

* Get rid of Darwin and force local node-pre-gyp

* Replace NAN_EXPORT with Nan:Export

Fixes gi.cc(373): error C3861: 'Export': identifier not found
On Windows, for unclear reason the Nan namespace is lost for NAN_EXPORT(exports, RegisterClass)

* Don't call g_source_add_unix_fd on Windows

* Add Windows build config

* Fix Windows include path

* Use g_free where appropriate

Fixes segfault on Windows

* Add GitHub workflow for Windows

* Add Node.js 16 Windows build

* Use appropriate Node.js version

* Ensure arg is zeroed

Fixes some segfaults on Windows, like
const val = new GObject.Value()
val.init(GObject.TYPE_STRING) <- crash

* Improve tests skipping

* Skip tests knows to fail on Windows

* Install gstreamer and libsoop to Windows

* Fix require test on Windows

* Don't free something that is not zero terminated

Fixes some crases on Windows.
Fixes 5 tests

* Ensure allocated memory is zeroed

Fixes 1 test on Windows

* GType is gsize, not gulong

GType is gsize is 8 bytes
gulong is 8 bytes on Linux and 4 bytes Windows

Fixes some segfaults on Windows
Fixes 3 tests on Windows

* Get rid of platform specific uint and ulong

* Use specific types to mute warnings on Linux

* Fix union__fields.js test on Windows

Number.MAX_SAFE_INTEGER is 8 bytes, but
vInt is gulong 4 bytes on Windows and 8 bytes on Linux

* Cleanup

* Cleanup #2

* Install gstreamer plugins

Fixes 1 test on Windows

* Partially enable conversion__array.js on Windows

See comment in code

* Fix generator

* Replace malloc/calloc with g_malloc

On Windows g_free memory allocated with malloc/calloc crashes

* Revert double-space

* Heap allocation on non-Linux only